version: "3.5"
services:
  php:
    build:
      dockerfile: .docker/php/Dockerfile
      context: .
      args:
        - UID=1000
        - GID=1000
    volumes:
      - ./:/app
      - /app/public/storage
    networks:
      - queue
      - broadcasting
  webserver:
    build:
      dockerfile: .docker/nginx/Dockerfile
      context: .
    ports:
      - 8000:80
    volumes:
      - .:/app
      - /app/public/storage
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - websocket
      - php
    networks:
      - broadcasting
  composer:
    image: composer:latest
    volumes:
        - ./:/app
        - ./.composer:/composer
  beanstalk:
    image: schickling/beanstalkd:latest
    networks:
      - queue
  mariadb:
    image: mariadb:latest
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - queue
  redis:
    image: redis:5
    networks:
      - broadcasting
  frontend:
    build:
      dockerfile: .docker/frontend/Dockerfile
      context: .
    volumes:
      - ./webpack.mix.js:/app/webpack.mix.js
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./resources:/app/resources
      - ./public:/app/public
    command: [ 'npm', 'run', 'watch-poll' ]
  websocket:
    build:
      dockerfile: .docker/websocket/Dockerfile
      context: .
    working_dir: /myapp
    depends_on:
      - redis
    networks:
      - broadcasting
    volumes:
      - ./:/myapp
networks:
  queue:
  broadcasting:
